#include "color_converter.h"
#include "shared/log.h"

#include "shaders/bgra_to_nv12.h"   // generated by fxc (CMake gpur_compile_hlsl)

namespace gpur::core::convert {

namespace {
struct ParamsCb {
    uint32_t width;
    uint32_t height;
    uint32_t full_range;
    uint32_t _pad;
};
} // namespace

Result<std::unique_ptr<ColorConverter>> ColorConverter::create(std::shared_ptr<D3dContext> ctx) {
    auto self  = std::unique_ptr<ColorConverter>(new ColorConverter());
    self->ctx_ = std::move(ctx);
    if (auto r = self->initialise(); !r) return err(std::move(r.error()));
    return self;
}

ColorConverter::~ColorConverter() = default;

Result<void> ColorConverter::initialise() {
    HRESULT hr = ctx_->device()->CreateComputeShader(
        g_bgra_to_nv12_cs, sizeof(g_bgra_to_nv12_cs), nullptr, &shader_);
    if (FAILED(hr)) {
        return err(Error::from_hresult(hr, "CreateComputeShader(bgra_to_nv12) failed"));
    }

    D3D11_BUFFER_DESC bd{};
    bd.ByteWidth      = sizeof(ParamsCb);
    bd.Usage          = D3D11_USAGE_DEFAULT;
    bd.BindFlags      = D3D11_BIND_CONSTANT_BUFFER;
    hr = ctx_->device()->CreateBuffer(&bd, nullptr, &cbuffer_);
    if (FAILED(hr)) {
        return err(Error::from_hresult(hr, "CreateBuffer(params) failed"));
    }
    return ok();
}

Result<void> ColorConverter::convert(ID3D11Texture2D* src, ID3D11Texture2D* dst) {
    if (!src || !dst) return err(Error::make(Error::Code::InvalidArgument, "convert: null texture"));

    D3D11_TEXTURE2D_DESC sd{}; src->GetDesc(&sd);
    D3D11_TEXTURE2D_DESC dd{}; dst->GetDesc(&dd);

    if (dd.Format != DXGI_FORMAT_NV12) {
        return err(Error::make(Error::Code::InvalidArgument, "dst must be DXGI_FORMAT_NV12"));
    }
    if (sd.Width != dd.Width || sd.Height != dd.Height) {
        return err(Error::make(Error::Code::InvalidArgument, "src and dst dimensions must match"));
    }

    auto* dev = ctx_->device();

    // SRV for the BGRA source.
    ComPtr<ID3D11ShaderResourceView> srv;
    {
        D3D11_SHADER_RESOURCE_VIEW_DESC vd{};
        vd.Format              = sd.Format;
        vd.ViewDimension       = D3D11_SRV_DIMENSION_TEXTURE2D;
        vd.Texture2D.MipLevels = 1;
        if (HRESULT hr = dev->CreateShaderResourceView(src, &vd, &srv); FAILED(hr)) {
            return err(Error::from_hresult(hr, "CreateSRV(BGRA) failed"));
        }
    }

    // UAVs for the Y and UV planes of the NV12 destination.
    ComPtr<ID3D11UnorderedAccessView> uav_y;
    {
        D3D11_UNORDERED_ACCESS_VIEW_DESC vd{};
        vd.Format        = DXGI_FORMAT_R8_UNORM;
        vd.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
        if (HRESULT hr = dev->CreateUnorderedAccessView(dst, &vd, &uav_y); FAILED(hr)) {
            return err(Error::from_hresult(hr, "CreateUAV(Y plane) failed"));
        }
    }
    ComPtr<ID3D11UnorderedAccessView> uav_uv;
    {
        D3D11_UNORDERED_ACCESS_VIEW_DESC vd{};
        vd.Format        = DXGI_FORMAT_R8G8_UNORM;
        vd.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
        if (HRESULT hr = dev->CreateUnorderedAccessView(dst, &vd, &uav_uv); FAILED(hr)) {
            return err(Error::from_hresult(hr, "CreateUAV(UV plane) failed"));
        }
    }

    ParamsCb cb{sd.Width, sd.Height, /*full_range=*/0, 0};

    auto* ic = ctx_->immediate();
    std::scoped_lock g(ctx_->immediate_mutex());

    ic->UpdateSubresource(cbuffer_.Get(), 0, nullptr, &cb, 0, 0);

    ic->CSSetShader(shader_.Get(), nullptr, 0);
    ic->CSSetConstantBuffers(0, 1, cbuffer_.GetAddressOf());
    ic->CSSetShaderResources(0, 1, srv.GetAddressOf());

    ID3D11UnorderedAccessView* uavs[] = {uav_y.Get(), uav_uv.Get()};
    ic->CSSetUnorderedAccessViews(0, 2, uavs, nullptr);

    UINT gx = (sd.Width  + 7) / 8;
    UINT gy = (sd.Height + 7) / 8;
    ic->Dispatch(gx, gy, 1);

    // Unbind so the encoder can read.
    ID3D11UnorderedAccessView* null_uavs[2] = {nullptr, nullptr};
    ic->CSSetUnorderedAccessViews(0, 2, null_uavs, nullptr);
    ID3D11ShaderResourceView* null_srv = nullptr;
    ic->CSSetShaderResources(0, 1, &null_srv);

    return ok();
}

} // namespace gpur::core::convert
